# File: k8/deployment.yml
# Two containers in two Services. This is more appropiate for cases where each container needs their own public port number.
# 2022-02-25 | CR

---
apiVersion: v1
kind: Service
metadata:
  name: fynappfront
spec:
  selector:
    app: fynappfront
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3001
      # Port to forward to inside the pod
      targetPort: 3001
      # Port accessible outside cluster
      # The range of valid ports is 30000-32767
      nodePort: 30011
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: fynappback
spec:
  selector:
    app: fynappback
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 5000
      # Port to forward to inside the pod
      targetPort: 5000
      # Port accessible outside cluster
      #  The range of valid ports is 30000-32767
      nodePort: 30015
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fynappfrontdep
  labels:
    app: fynappfront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fynappfront
  template:
    metadata:
      labels:
        app: fynappfront
    spec:
      containers:

        - name: fynapp-frontend
          image: mediabros/fynapp_frontend:v0.1.1-amd64
          ports:
            - containerPort: 3001
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                secretKeyRef:
                  name: fynappsecrets
                  key: fynapp_backend_public_url

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fynappbackdep
  labels:
    app: fynappback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fynappback
  template:
    metadata:
      labels:
        app: fynappback
    spec:
      containers:
        - name: fynapp-backend
          image: mediabros/fynapp_backend:v0.1.1-amd64
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "fynapp_api"
            - name: FLASK_ENV
              value: "fynapp_api"
            - name: FYNAPP_DB_NAME
              value: "fynapp_dev"
            - name: FLASK_DEBUG
              value: "1"
            - name: FYNAPP_DB_URI
              valueFrom:
                secretKeyRef:
                  name: fynappsecrets
                  key: fynapp_db_uri
            - name: FYNAPP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fynappsecrets
                  key: fynapp_secret_key
