# File: k8/deployment.yml
# 2022-02-25 | CR

---
apiVersion: v1
kind: Service
metadata:
  name: fynappservice
spec:
  selector:
    app: fynapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 3001
      # Port accessible outside cluster
      # nodePort: 80
      #  80: provided port is not in the valid range. The range of valid ports is 30000-32767
      nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fynappdeployment
  labels:
    app: fynapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fynapp
  template:
    metadata:
      labels:
        app: fynapp
    spec:
      containers:

        - name: fynapp-frontend
          image: mediabros/fynapp_frontend:v0.1.1-amd64
          ports:
            - containerPort: 3001
          env:
            - name: BACKEND_URL
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: REACT_APP_API_URL
              value: "https://${BACKEND_URL}:5000"

        - name: fynapp-backend
          image: mediabros/fynapp_backend:v0.1.1-amd64
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: "fynapp_api"
            - name: FLASK_ENV
              value: "fynapp_api"
            - name: FYNAPP_DB_NAME
              value: "fynapp_dev"
            - name: FLASK_DEBUG
              value: "0"
            - name: FYNAPP_DB_URI
              valueFrom:
                secretKeyRef:
                  name: fynappsecrets
                  key: fynapp_db_uri
            - name: FYNAPP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fynappsecrets
                  key: fynapp_secret_key
